version: "3.3"

services:

    mysql:
        build: ../db/
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        container_name: dbingsoft
        networks:
            - red
        command: --default-authentication-plugin=mysql_native_password

networks:
    red:
        external: true
 