version: "1.1"

services:

    # articles:
    #     build: ../articles_microservice/
    #     ports:
    #         - "7000:7000"
    #     depends_on:
    #         - mysql

    mysql:
        build: ../db/
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        container_name: db_ingsoft

        