version: "3.3"

services:
  
  shipping:
    # container_name: shipping_microservice
    build: .
    # ports:
    #   - "6000:7000"
    environment:
     - DB_HOST=dbingsoft
     - DB_USER=root
     - DB_PASSWORD=fenske12
     - DB_PORT=3306
     - DB_DATABASE=StockShipper
     - ARTICLES_API=https://article.order.localhost
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shipping.rule=Host(`shipping.order.localhost`)"
      - "traefik.http.routers.shipping.tls=true"
      - "traefik.http.services.shipping.loadbalancer.server.port=7000"
      - "traefik.docker.network=red"
      
    networks:
      - red

networks:
    red:
        external: true
