version: "3.3"

services:
  
  shipping:
    container_name: shipping_microservice
    build: .
    ports:
      - "6000:7000"
    environment:
     - DB_HOST=dbingsoft
     - DB_USER=root
     - DB_PASSWORD=fenske12
     - DB_PORT=3306
     - DB_DATABASE=StockShipper

    networks:
      - red

networks:
    red:
        external: true
