version: "3.3"

services:

    shipping:
        build: .
        # ports: 
        #     - "7000:7000"
        # container_name: article_microservice
        environment:
            - DB_HOST=dbingsoft
            - DB_PORT=3306
            - DB_DATABASE=StockShipper
            - DB_USER=root
            - DB_PASSWORD=fenske12
            - VIRTUAL_HOST=shipping.order.localhost
            - ARTICLE_API=https://article.order.localhost

        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.shipping.rule=Host(`shipping.order.localhost`)"
            - "traefik.http.routers.shipping.tls=true"
            - "traefik.http.services.shipping.loadbalancer.server.port=7000"
            - "traefik.docker.network=red"

            - "traefik.http.services.shipping.loadbalancer.server.scheme=http"
        # dns_search:
        #     - traefik.order.localhost
            
        networks:
            - red

networks:
    red:
        external: true