version: '3'

services:

  traefik: 
    image: traefik:v2.9
    container_name: traefik_proxy 
    restart: unless-stopped
    # security_opt:
    #   - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true" 
      
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro # Para que traefik puede escuchar los eventos de docker
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro # Configuración de traefik
      - ./config/config.yml:/etc/traefik/config.yml:ro # Configuración de traefik
      - ./certs:/etc/traefik/certs:ro # Certificados de traefik
    networks:
      red: 
        aliases:
          - article.order.localhost
          - shipping.order.localhost
        

networks:
  red:
    external: true