global:
  sendAnonymousUsage: false

entryPoints: 
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: ":443"


api: #ocultando los servicios 
  insecure: true
  dashboard: true


log: 

  level: INFO  
  format: common  
  
providers: 
  docker:
    endpoint: "unix:///var/run/docker.sock" 
    exposedByDefault: false 
    watch: true 
  
  file:
    filename: /etc/traefik/config.yml
    watch: true

  consulCatalog:
    refreshInterval: 10s
    connectAware: true
    serviceName: "traefik"
    prefix: traefik
    exposedByDefault: false 
    endpoint: 
      address: "consul:8500"